# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc9286bcc05ae3c80d93d922d6acd59eaddf2bbe63efd027a0695551a27edca068e8ef34a205ca7e73abece05aff65aa11608e33ec65676455397eb702a02fd

test:
  secret_key_base: 48af8861c6e71306d4bf88130c20d808b9a8cf879a5f4df207c1367583bf6b9e37f5d82e5f770e920a0d1f5afa546368e8e1f2cee890bd1c1e0fa8e7ad639aaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
